name: Android + Release
on: workflow_dispatch
jobs:
  Build-gcc:
    strategy:
      matrix:
        build_type: [EXTERNAL_DATA, EXTERNAL]
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r15c
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Restore Previous Cache
        if: ${{ always() }}
        id: cache-debug-build-android-restore-gcc
        uses: actions/cache/restore@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build-gcc
      - name: Installing Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib git extension-androidtools https://github.com/mcagabe19-stuff/extension-androidtools.git
          haxelib install flixel-addons 3.0.2 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel 5.2.2 --quiet
          haxelib git hxCodec https://github.com/mcagabe19-stuff/hxCodec.git
          # haxelib install hscript --quiet
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp.git
          haxelib install lime 7.9.0 --quiet
          haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit.git
          haxelib install openfl 9.2.1 --quiet
          haxelib install SScript 5.0.0 --quiet
          # haxelib install tjson 1.4.0 --quiet
          haxelib git extension-orientation https://github.com/HaxeExtension/extension-orientation.git
          cp /home/runner/work/FNF-PsychEngine-Mobile/FNF-PsychEngine-Mobile/art/CustomManifest.xml /home/runner/haxelib/lime/7,9,0/templates/android/template/app/src/main/AndroidManifest.xml
      - name: List Haxelibs
        run: haxelib list
      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: haxelib run lime build android -D ${{ matrix.build_type }} -D NO_PRECOMPILED_HEADERS -release
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni
      - name: Clear Previous Cache
        if: |
          ${{ always() }} ||
          ( ${{ matrix.build_type }} == 'EXTERNAL_DATA' )
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-android-build-gcc") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }
      - name: Save Current Cache
        if: |
          ${{ always() }} ||
          ( ${{ matrix.build_type }} == 'EXTERNAL_DATA' )
        id: cache-release-build-android-save-gcc
        uses: actions/cache/save@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build-gcc
      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: androidBuild-gcc-${{ matrix.build_type }}
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
  Releaser:
    needs: Build-gcc
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Gcc Build (External Data)
        uses: actions/download-artifact@v3
        with:
           name: androidBuild-gcc-EXTERNAL_DATA
           path: /home/runner
      - name: Rename Gcc Build
        run: mv /home/runner/PsychEngine-release.apk /home/runner/PsychEngine-gcc-release.apk
      - name: Publish The Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "0.7.1h-release4"
          title: "0.7.1h Android Release 4"
          files: |
            /home/runner/PsychEngine-gcc-release.apk
